# fly.toml app configuration file generated for platzi-node-api on 2023-05-08T17:07:24-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "platzi-node-api"
primary_region = "qro"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
