service: platzi-postgresql-node-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 1024
  timeout: 10
  region: us-east-2

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
